version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/factcheck
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ../backend:/app
    networks:
      - factcheck-network

  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=factcheck
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - factcheck-network

  redis:
    build:
      context: .
      dockerfile: redis.Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - factcheck-network

networks:
  factcheck-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
